### ISSUE TITLE
BrokenPipeError

### ISSUE THREAD

**Issue by jkanche** [lhqing/ALLCools#2]
I am not sure whats happening here but the package fails to run properly on both linux and windows (including WSL). If you already have experienced this before, let me know! 

Thanks,
Jay

```
⋊> /m/c/U/j/D/p/a/files allcools allc-to-bigwig --allc_path ./Round2.1-1.allc.tsv.gz --output_prefix "res-2.1-1" --chrom_size_path ../mm10.chrom.sizes  --mc_contexts CHN CGN --bin_size 1 --remove_additional_chrom --cov_cutoff 99999 --cpu 4
command allc-to-bigwig
allc_path       ./Round2.1-1.allc.tsv.gz
output_prefix   res-2.1-1
chrom_size_path ../mm10.chrom.sizes
mc_contexts     ['CHN', 'CGN']
split_strand    False
bin_size        1
remove_additional_chrom True
region  None
cov_cutoff      99999
path_to_wigtobigwig     /home/jkanche/miniconda3/envs/allcl/bin/
cpu     4
Executing allc-to-bigwig...
Parallel extract ALLC
concurrent.futures.process._RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/jkanche/miniconda3/envs/allcl/lib/python3.7/concurrent/futures/process.py", line 232, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/home/jkanche/miniconda3/envs/allcl/lib/python3.7/site-packages/ALLCools/_extract_allc.py", line 337, in extract_allc
    [h.write(line_func(cur_line)) for h in context_handle[cur_line[3]]]
  File "/home/jkanche/miniconda3/envs/allcl/lib/python3.7/site-packages/ALLCools/_extract_allc.py", line 337, in <listcomp>
    [h.write(line_func(cur_line)) for h in context_handle[cur_line[3]]]
  File "/home/jkanche/miniconda3/envs/allcl/lib/python3.7/site-packages/ALLCools/_open.py", line 144, in write
    self._file.write(arg)
  File "/home/jkanche/miniconda3/envs/allcl/lib/python3.7/codecs.py", line 378, in write
    self.stream.write(data)
BrokenPipeError: [Errno 32] Broken pipe
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jkanche/miniconda3/envs/allcl/bin/allcools", line 8, in <module>
    sys.exit(main())
  File "/home/jkanche/miniconda3/envs/allcl/lib/python3.7/site-packages/ALLCools/__main__.py", line 1127, in main
    func(**args_vars)
  File "/home/jkanche/miniconda3/envs/allcl/lib/python3.7/site-packages/ALLCools/_allc_to_bigwig.py", line 174, in allc_to_bigwig
    cpu=cpu)
  File "/home/jkanche/miniconda3/envs/allcl/lib/python3.7/site-packages/ALLCools/_extract_allc.py", line 315, in extract_allc
    tabix=tabix)
  File "/home/jkanche/miniconda3/envs/allcl/lib/python3.7/site-packages/ALLCools/_extract_allc.py", line 139, in _extract_allc_parallel
    output_path_dict = future.result()
  File "/home/jkanche/miniconda3/envs/allcl/lib/python3.7/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/home/jkanche/miniconda3/envs/allcl/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by lhqing** [comment]
Hi Jay, I just tried the exact command but didn't get any error. Your error occurs when trying to write to a bgzip file, I wonder what's the bgzip version you are using (mine is 1.9)? Do you have authority writing to the current directory you ran that command?

I remember the conda default bgzip installation is an old version, you need to install htslib to get the newer version. 

I do have a more thorough installation tutorial that related to ALLCools in my other package, but I haven't got time to integrate them yet: https://cemba-data.readthedocs.io/en/latest/installation.html

Also, I never used windows to develop these codes, I don't promise this will work on windows.

**Comment by jkanche** [comment]
cool,  I think the issue was with bgzip. Installing version 1.9 fixed the error. Thanks for the help
