### ISSUE TITLE
Error: allcools generate-dataset 

### ISSUE THREAD

**Issue by kenrchandradoss** [lhqing/ALLCools#45]
Hi, 

I am trying to generate mcds file using a bunch of allc files that I downloaded from GSE130711. These are my commands and files. 

TSV file containing allc file names: 
sample1	GSM3748102_allc_181218_snm3Cseq_hs_21yr_BA10_UMB5577_1_UMB5577_2_A10_AD001_indexed.tsv.gz
sample2	GSM3748103_allc_181218_snm3Cseq_hs_21yr_BA10_UMB5577_1_UMB5577_2_A10_AD004_indexed.tsv.gz
sample3	GSM3748104_allc_181218_snm3Cseq_hs_21yr_BA10_UMB5577_1_UMB5577_2_A10_AD006_indexed.tsv.gz
sample4	GSM3748105_allc_181218_snm3Cseq_hs_21yr_BA10_UMB5577_1_UMB5577_2_A10_AD007_indexed.tsv.gz
sample5	GSM3748106_allc_181218_snm3Cseq_hs_21yr_BA10_UMB5577_1_UMB5577_2_A10_AD008_indexed.tsv.gz
sample6	GSM3748107_allc_181218_snm3Cseq_hs_21yr_BA10_UMB5577_1_UMB5577_2_A10_AD010_indexed.tsv.gz

command: 
`    allcools generate-dataset  \
    --allc_table files.txt \
    --output_path test.mcds \
    --chrom_size_path hg19.chrom.sizes \
    --obs_dim cell  \
    --cpu 10 \
    --chunk_size 50 \
    --regions chrom100k 100000 \
    --quantifiers chrom100k count CGN,CHN,CAN \
`

This is the error: 
`concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/kenrc/mambaforge/envs/mapping/lib/python3.7/concurrent/futures/process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/home/kenrc/mambaforge/envs/mapping/lib/python3.7/site-packages/ALLCools/count_matrix/dataset.py", line 256, in _count_single_zarr
    total_ds.to_zarr(output_path, mode="w")
  File "/home/kenrc/mambaforge/envs/mapping/lib/python3.7/site-packages/xarray/core/dataset.py", line 2050, in to_zarr
    safe_chunks=safe_chunks,
  File "/home/kenrc/mambaforge/envs/mapping/lib/python3.7/site-packages/xarray/backends/api.py", line 1402, in to_zarr
    stacklevel=4,  # for Dataset.to_zarr()
  File "/home/kenrc/mambaforge/envs/mapping/lib/python3.7/site-packages/xarray/backends/zarr.py", line 386, in open_group
    zarr_group = zarr.open_group(store, **open_kwargs)
NameError: name 'zarr' is not defined
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/kenrc/mambaforge/envs/mapping/bin/allcools", line 8, in <module>
    sys.exit(main())
  File "/home/kenrc/mambaforge/envs/mapping/lib/python3.7/site-packages/ALLCools/__main__.py", line 838, in main
    func(**args_vars)
  File "/home/kenrc/mambaforge/envs/mapping/lib/python3.7/site-packages/ALLCools/count_matrix/dataset.py", line 341, in generate_dataset
    chunk_path = f.result()
  File "/home/kenrc/mambaforge/envs/mapping/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/home/kenrc/mambaforge/envs/mapping/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
NameError: name 'zarr' is not defined`

Anything that I am missing? 

Thank you for your help in advance.

**Comment by kenrchandradoss** [comment]
To solve the error mentioned above and subsequent errors, please install the following packages in the environment

`
    # installed during allcools generate dataset
    pip install zarr
    pip install dask
    
    # installed while running the clustering ipyb
    pip install scanpy  
    pip install opentsne
    pip install leidenalg
    pip install imblearn
    pip install load
`
